apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-snap-1-pvc
  namespace: awesome
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  dataSource:
    name: my-snap-1
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: exoscale-sbs

