name: sscs

on:
  workflow_dispatch:
  push:

jobs:
  gitsign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: chainguard-dev/actions/setup-gitsign@main
      - name: verify commit signature
        shell: bash
        run: |
          gitsign verify --certificate-identity-regexp='sauterp.*' --certificate-oidc-issuer='https://github.com/login/oauth' HEAD
